import nbformat as nbf

nb = nbf.v4.new_notebook()

cells = [
    nbf.v4.new_markdown_cell(
        "# Bengali LLM Hallucination Detection — Winning Solution Pipeline\n\n"
        "This notebook implements an advanced split-pipeline solution to predict whether a Bengali LLM response is faithful (`label = 1`) or hallucinated (`label = 0`).\n\n"
        "- **Open-Book Task**: Evaluates lexical overlap features and semantic entailment via a cross-lingual NLI model (`mDeBERTa-v3-base-mnli-xnli`).\n"
        "- **Closed-Book Task**: Fact-checks the response using `Qwen2.5-1.5B-Instruct` (or `Qwen2.5-7B-Instruct`)."
    ),
    nbf.v4.new_code_cell(
        "import os\n"
        "import json\n"
        "import re\n"
        "import difflib\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import torch\n"
        "from sklearn.model_selection import StratifiedKFold\n"
        "from sklearn.linear_model import LogisticRegression\n"
        "from sklearn.metrics import f1_score, classification_report\n"
        "from tqdm.auto import tqdm\n"
        "from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForCausalLM\n\n"
        "# Detect environment\n"
        "IS_KAGGLE = os.path.exists(\"/kaggle/input\")\n"
        "print(f\"Running on Kaggle: {IS_KAGGLE}\")"
    ),
    nbf.v4.new_code_cell(
        "# Paths\n"
        "if IS_KAGGLE:\n"
        "    TRAIN_PATH = \"/kaggle/input/bengali-hallucination/dataset samples.json\"\n"
        "    TEST_PATH = \"/kaggle/input/bengali-hallucination/test set.csv\"\n"
        "    \n"
        "    # We use offline datasets from Kaggle\n"
        "    NLI_MODEL_PATH = \"/kaggle/input/vladyslav0/mdeberta-v3-base-mnli-xnli-model\"\n"
        "    # Using Qwen 2.5 1.5B Instruct for offline speed and accuracy\n"
        "    QWEN_MODEL_PATH = \"/kaggle/input/qwen-2-5-1-5b-instruct-offline\"\n"
        "else:\n"
        "    TRAIN_PATH = \"dataset samples.json\"\n"
        "    TEST_PATH = \"test set.csv\"\n"
        "    \n"
        "    NLI_MODEL_PATH = \"MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7\"\n"
        "    QWEN_MODEL_PATH = \"Qwen/Qwen2.5-1.5B-Instruct\"\n\n"
        "print(f\"Train Path: {TRAIN_PATH}\")\n"
        "print(f\"Test Path: {TEST_PATH}\")"
    ),
    nbf.v4.new_code_cell(
        "# Load Training Data\n"
        "with open(TRAIN_PATH, encoding=\"utf-8\") as f:\n"
        "    train_records = json.load(f)\n"
        "train_df = pd.DataFrame(train_records)\n\n"
        "# Load Test Data\n"
        "test_df = pd.read_csv(TEST_PATH)\n\n"
        "print(f\"Train shape: {train_df.shape}\")\n"
        "print(f\"Test shape: {test_df.shape}\")"
    ),
    nbf.v4.new_code_cell(
        "# Clean context helper\n"
        "NO_CONTEXT_VALUES = {\"\", \"nan\", \"NaN\", \"[NULL]\", None}\n\n"
        "def clean_context(value):\n"
        "    if pd.isna(value) or str(value).strip() in NO_CONTEXT_VALUES:\n"
        "        return \"\"\n"
        "    return str(value).strip()\n\n"
        "for df in [train_df, test_df]:\n"
        "    df[\"context\"] = df[\"context\"].apply(clean_context)\n"
        "    df[\"has_context\"] = df[\"context\"].str.len() > 0\n"
        "    df[\"prompt_bn\"] = df[\"prompt_bn\"].astype(str)\n"
        "    df[\"response_bn\"] = df[\"response_bn\"].astype(str)\n\n"
        "print(\"Train has_context distribution:\")\n"
        "print(train_df[\"has_context\"].value_counts())\n"
        "print(\"\\nTest has_context distribution:\")\n"
        "print(test_df[\"has_context\"].value_counts())"
    ),
    nbf.v4.new_code_cell(
        "# Lexical Feature Engineering Functions\n"
        "def get_jaccard_similarity(c, r):\n"
        "    words_c = set(c.split())\n"
        "    words_r = set(r.split())\n"
        "    if not words_c or not words_r:\n"
        "        return 0.0\n"
        "    return len(words_c.intersection(words_r)) / len(words_c.union(words_r))\n\n"
        "def get_char_overlap(c, r):\n"
        "    chars_c = set(c)\n"
        "    chars_r = set(r)\n"
        "    if not chars_r:\n"
        "        return 0.0\n"
        "    return len(chars_c.intersection(chars_r)) / len(chars_r)\n\n"
        "def get_exact_match(c, r):\n"
        "    return 1.0 if r in c else 0.0\n\n"
        "def get_lcs_ratio(c, r):\n"
        "    seq = difflib.SequenceMatcher(None, c, r)\n"
        "    return seq.ratio()\n\n"
        "def extract_numbers(text):\n"
        "    return set(re.findall(r'[0-9০-৯]+', text))\n\n"
        "def get_number_mismatch(c, r):\n"
        "    nums_c = extract_numbers(c)\n"
        "    nums_r = extract_numbers(r)\n"
        "    if not nums_r:\n"
        "        return 0.0\n"
        "    return 1.0 if not nums_r.issubset(nums_c) else 0.0\n\n"
        "def extract_lexical_features(df):\n"
        "    features = []\n"
        "    for row in df.itertuples():\n"
        "        c, r = row.context, row.response_bn\n"
        "        features.append({\n"
        "            \"jaccard\": get_jaccard_similarity(c, r),\n"
        "            \"char_overlap\": get_char_overlap(c, r),\n"
        "            \"exact_match\": get_exact_match(c, r),\n"
        "            \"lcs_ratio\": get_lcs_ratio(c, r),\n"
        "            \"num_mismatch\": get_number_mismatch(c, r)\n"
        "        })\n"
        "    return pd.DataFrame(features)"
    ),
    nbf.v4.new_code_cell(
        "# NLI Model Setup and Extraction\n"
        "print(f\"Loading NLI Model from {NLI_MODEL_PATH}...\")\n"
        "try:\n"
        "    nli_tokenizer = AutoTokenizer.from_pretrained(NLI_MODEL_PATH)\n"
        "    nli_model = AutoModelForSequenceClassification.from_pretrained(NLI_MODEL_PATH)\n"
        "    device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n"
        "    nli_model.to(device)\n"
        "    nli_model.eval()\n"
        "    print(f\"Model successfully loaded on {device}.\")\n"
        "    has_nli = True\n"
        "except Exception as e:\n"
        "    print(f\"Could not load NLI model: {e}. Will fallback to lexical-only features.\")\n"
        "    has_nli = False"
    ),
    nbf.v4.new_code_cell(
        "def extract_nli_features(df, batch_size=32):\n"
        "    if not has_nli:\n"
        "        return pd.DataFrame({\"nli_entailment\": [0.5]*len(df), \"nli_contradiction\": [0.5]*len(df)})\n"
        "    \n"
        "    premises = df[\"context\"].tolist()\n"
        "    hypotheses = df[\"response_bn\"].tolist()\n"
        "    \n"
        "    entail_scores = []\n"
        "    contra_scores = []\n"
        "    \n"
        "    for i in tqdm(range(0, len(premises), batch_size), desc=\"Running NLI inference\"):\n"
        "        batch_prem = premises[i:i+batch_size]\n"
        "        batch_hypo = hypotheses[i:i+batch_size]\n"
        "        \n"
        "        inputs = nli_tokenizer(\n"
        "            batch_prem, \n"
        "            batch_hypo, \n"
        "            padding=True, \n"
        "            truncation=True, \n"
        "            max_length=512,\n"
        "            return_tensors=\"pt\"\n"
        "        ).to(device)\n"
        "        \n"
        "        with torch.no_grad():\n"
        "            outputs = nli_model(**inputs)\n"
        "            probs = torch.softmax(outputs.logits, dim=-1).cpu().numpy()\n"
        "            \n"
        "        # MoritzLaurer labels: 0: entailment, 1: neutral, 2: contradiction\n"
        "        for p in probs:\n"
        "            entail_scores.append(p[0])\n"
        "            contra_scores.append(p[2])\n"
        "            \n"
        "    df_nli = pd.DataFrame({\n"
        "        \"nli_entailment\": entail_scores,\n"
        "        \"nli_contradiction\": contra_scores\n"
        "    })\n"
        "    return df_nli"
    ),
    nbf.v4.new_code_cell(
        "# Open-book validation: extract open-book subset of training data\n"
        "train_ob = train_df[train_df[\"has_context\"]].copy().reset_index(drop=True)\n"
        "print(f\"Open-book training samples: {len(train_ob)}\")\n\n"
        "# Extract lexical features\n"
        "lex_feats_train = extract_lexical_features(train_ob)\n"
        "# Extract NLI features\n"
        "nli_feats_train = extract_nli_features(train_ob)\n\n"
        "# Combine features\n"
        "X_train_ob = pd.concat([lex_feats_train, nli_feats_train], axis=1)\n"
        "y_train_ob = train_ob[\"label\"].values\n\n"
        "print(\"Features columns:\", X_train_ob.columns.tolist())\n"
        "X_train_ob.head()"
    ),
    nbf.v4.new_code_cell(
        "# Perform cross-validation on open-book subset\n"
        "cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n"
        "cv_preds = np.zeros(len(train_ob))\n\n"
        "for train_idx, val_idx in cv.split(X_train_ob, y_train_ob):\n"
        "    X_tr, y_tr = X_train_ob.iloc[train_idx], y_train_ob[train_idx]\n"
        "    X_val, y_val = X_train_ob.iloc[val_idx], y_train_ob[val_idx]\n"
        "    \n"
        "    clf = LogisticRegression(class_weight=\"balanced\", random_state=42)\n"
        "    clf.fit(X_tr, y_tr)\n"
        "    cv_preds[val_idx] = clf.predict(X_val)\n\n"
        "print(\"Open-book CV Report:\")\n"
        "print(classification_report(y_train_ob, cv_preds, target_names=[\"Hallucinated\", \"Faithful\"]))"
    ),
    nbf.v4.new_code_cell(
        "# Train the final open-book model on the full open-book training data\n"
        "ob_classifier = LogisticRegression(class_weight=\"balanced\", random_state=42)\n"
        "ob_classifier.fit(X_train_ob, y_train_ob)\n"
        "print(\"Open-book model trained successfully.\")"
    ),
    nbf.v4.new_code_cell(
        "# Closed-Book Fact Checking using Qwen 2.5\n"
        "# Set local_run = True to bypass if testing locally without GPU/weights\n"
        "local_run = not IS_KAGGLE\n\n"
        "if local_run:\n"
        "    print(\"Local run mode: Skipping Qwen setup. Will use standard TF-IDF + Logistic Regression.\")\n"
        "    has_qwen = False\n"
        "else:\n"
        "    print(f\"Loading Qwen Model from {QWEN_MODEL_PATH}...\")\n"
        "    try:\n"
        "        qwen_tokenizer = AutoTokenizer.from_pretrained(QWEN_MODEL_PATH)\n"
        "        qwen_tokenizer.padding_side = \"left\"\n"
        "        if qwen_tokenizer.pad_token_id is None:\n"
        "            qwen_tokenizer.pad_token_id = qwen_tokenizer.eos_token_id\n"
        "            \n"
        "        qwen_model = AutoModelForCausalLM.from_pretrained(\n"
        "            QWEN_MODEL_PATH,\n"
        "            torch_dtype=torch.float16,\n"
        "            device_map=\"auto\"\n"
        "        )\n"
        "        print(\"Qwen Model loaded successfully.\")\n"
        "        has_qwen = True\n"
        "    except Exception as e:\n"
        "        print(f\"Could not load Qwen model: {e}. Will fallback to TF-IDF.\")\n"
        "        has_qwen = False"
    ),
    nbf.v4.new_code_cell(
        "def run_qwen_factchecker(df, batch_size=8):\n"
        "    if not has_qwen:\n"
        "        return [0] * len(df) # Fallback\n"
        "    \n"
        "    prompts = df[\"prompt_bn\"].tolist()\n"
        "    responses = df[\"response_bn\"].tolist()\n"
        "    \n"
        "    results = []\n"
        "    \n"
        "    for i in tqdm(range(0, len(prompts), batch_size), desc=\"Running Qwen fact-checking\"):\n"
        "        batch_p = prompts[i:i+batch_size]\n"
        "        batch_r = responses[i:i+batch_size]\n"
        "        \n"
        "        texts = []\n"
        "        for p, r in zip(batch_p, batch_r):\n"
        "            messages = [\n"
        "                {\"role\": \"system\", \"content\": \"আপনি একটি প্রশ্নের উত্তর সঠিক নাকি ভুল তা যাচাই করছেন। অতিরিক্ত কোনো কথা না বলে শুধুমাত্র একটি শব্দে উত্তর দিন: 'হ্যাঁ' (যদি সঠিক হয়) অথবা 'না' (যদি ভুল হয়)।\"},\n"
        "                {\"role\": \"user\", \"content\": f\"প্রশ্ন: {p}\\nউত্তর: {r}\\nউপরের উত্তরটি কি সঠিক? হ্যাঁ অথবা না বলুন।\"}\n"
        "            ]\n"
        "            text = qwen_tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n"
        "            texts.append(text)\n"
        "            \n"
        "        inputs = qwen_tokenizer(texts, padding=True, return_tensors=\"pt\").to(qwen_model.device)\n"
        "        \n"
        "        with torch.no_grad():\n"
        "            generated_ids = qwen_model.generate(\n"
        "                **inputs,\n"
        "                max_new_tokens=8,\n"
        "                temperature=0.0,\n"
        "                do_sample=False,\n"
        "                pad_token_id=qwen_tokenizer.pad_token_id\n"
        "            )\n"
        "            \n"
        "        input_len = inputs.input_ids.shape[1]\n"
        "        for gen_ids in generated_ids:\n"
        "            gen_text = qwen_tokenizer.decode(gen_ids[input_len:], skip_special_tokens=True).strip()\n"
        "            if \"হ্যাঁ\" in gen_text or \"সঠিক\" in gen_text:\n"
        "                results.append(1)\n"
        "            else:\n"
        "                results.append(0)\n"
        "                \n"
        "    return results"
    ),
    nbf.v4.new_code_cell(
        "# Verify/Train Closed-book on Training Data\n"
        "train_cb = train_df[~train_df[\"has_context\"]].copy().reset_index(drop=True)\n"
        "print(f\"Closed-book training samples: {len(train_cb)}\")\n\n"
        "if local_run or not has_qwen:\n"
        "    # Use standard prompt/response TF-IDF for local verification/fallback\n"
        "    from sklearn.feature_extraction.text import TfidfVectorizer\n"
        "    vectorizer = TfidfVectorizer(max_features=5000, analyzer='char_wb', ngram_range=(2,4))\n"
        "    X_train_cb = vectorizer.fit_transform(train_cb[\"prompt_bn\"] + \" \" + train_cb[\"response_bn\"])\n"
        "    y_train_cb = train_cb[\"label\"].values\n"
        "    \n"
        "    cb_clf = LogisticRegression(class_weight=\"balanced\", random_state=42)\n"
        "    cb_clf.fit(X_train_cb, y_train_cb)\n"
        "    cb_preds = cb_clf.predict(X_train_cb)\n"
        "    print(\"Local validation closed-book classification report (TF-IDF + LR):\")\n"
        "    print(classification_report(y_train_cb, cb_preds))\n"
        "else:\n"
        "    cb_preds = run_qwen_factchecker(train_cb)\n"
        "    print(\"Qwen Closed-Book Fact-Checking Report:\")\n"
        "    print(classification_report(train_cb[\"label\"].values, cb_preds, target_names=[\"Hallucinated\", \"Faithful\"]))"
    ),
    nbf.v4.new_code_cell(
        "# Predict on Test Set\n\n"
        "# Split Test Set\n"
        "test_ob = test_df[test_df[\"has_context\"]].copy().reset_index(drop=True)\n"
        "test_cb = test_df[~test_df[\"has_context\"]].copy().reset_index(drop=True)\n\n"
        "print(f\"Test Open-book samples: {len(test_ob)}\")\n"
        "print(f\"Test Closed-book samples: {len(test_cb)}\")"
    ),
    nbf.v4.new_code_cell(
        "# 1. Open-book Predictions\n"
        "print(\"Extracting features for Open-Book test rows...\")\n"
        "lex_feats_test = extract_lexical_features(test_ob)\n"
        "nli_feats_test = extract_nli_features(test_ob)\n"
        "X_test_ob = pd.concat([lex_feats_test, nli_feats_test], axis=1)\n\n"
        "print(\"Predicting Open-Book test rows...\")\n"
        "test_ob[\"label\"] = ob_classifier.predict(X_test_ob)"
    ),
    nbf.v4.new_code_cell(
        "# 2. Closed-book Predictions\n"
        "print(\"Predicting Closed-Book test rows...\")\n"
        "if local_run or not has_qwen:\n"
        "    # Local fallback prediction\n"
        "    X_test_cb = vectorizer.transform(test_cb[\"prompt_bn\"] + \" \" + test_cb[\"response_bn\"])\n"
        "    test_cb[\"label\"] = cb_clf.predict(X_test_cb)\n"
        "else:\n"
        "    test_cb[\"label\"] = run_qwen_factchecker(test_cb)"
    ),
    nbf.v4.new_code_cell(
        "# Combine predictions and save to submission.csv\n"
        "submission_ob = test_ob[[\"id\", \"label\"]]\n"
        "submission_cb = test_cb[[\"id\", \"label\"]]\n"
        "submission_all = pd.concat([submission_ob, submission_cb], axis=0).sort_values(\"id\").reset_index(drop=True)\n\n"
        "# Ensure ID is integer\n"
        "submission_all[\"id\"] = submission_all[\"id\"].astype(int)\n"
        "submission_all[\"label\"] = submission_all[\"label\"].astype(int)\n\n"
        "# Check distribution\n"
        "print(\"Submission label distribution:\")\n"
        "print(submission_all[\"label\"].value_counts())\n\n"
        "submission_all.to_csv(\"submission.csv\", index=False)\n"
        "print(\"submission.csv saved successfully!\")"
    )
]

nb['cells'] = cells

with open("solution_pipeline.ipynb", "w", encoding="utf-8") as f:
    nbf.write(nb, f)

print("solution_pipeline.ipynb successfully generated!")
